### ISSUE TITLE
It would be nice to have file context menus

### ISSUE THREAD

**Issue by ixth** [gOATiful/para-shortcuts#16]

**Comment by gOATiful** [comment]
Hey,
thanks for reaching out!

Could you specify in more detail what you mean? :)

**Comment by ixth** [comment]
I'm talking about file context menus, for me it feels more convenient than palette commands:

<img width="304" alt="Screenshot 2022-11-04 at 10 37 33" src="https://user-images.githubusercontent.com/107447/199941487-e2d3204d-eaa1-48ba-a991-7b7e53974603.png"> <img width="304" alt="Screenshot 2022-11-04 at 10 37 54" src="https://user-images.githubusercontent.com/107447/199941493-8a3bb6c6-7f64-4405-a659-a4e688fc629a.png">

I'll make a PR in an hour.

**Comment by gOATiful** [comment]
Oh, get it. Thanks! If you don't create it, I will add it later today.
