### ISSUE TITLE
Generated Resource folder spelled incorrectly 

### ISSUE THREAD

**Issue by bramses** [gOATiful/para-shortcuts#9]
<img width="120" alt="Screen Shot 2022-01-25 at 5 01 05 AM" src="https://user-images.githubusercontent.com/3282661/150964883-59508884-616a-4402-bc88-1f0b6c1e48cb.png">

should be Resource (or ideally, "Resources" [plural] since it will hold many different resources)

**Comment by gOATiful** [comment]
oh yes, you are right! I changed it already.

Naming: Ii took them from the definitions of the PARA method, but further down it is used as plural.
Nevertheless, you can change the names in the plugin settings
